{{- if .Values.patroni.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    name: postgres-credentials
    automation.infra/secret-change: "true"
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: postgres-credentials
data:
  password: {{ ( include "postgres.adminPassword" . ) | b64enc }}
  username: {{ ( include "postgres.adminUser" . ) | b64enc }}
type: Opaque
{{ end }}